baseurl: ''
canonifyurls: true
languageCode: en-us
theme: hugo-octopress
title: Kyle Lieber
pygmentscodefences: true
pygmentsStyle: monokai
menu:
  main:
    - name: Restdocs Spec Maven Plugin
      url: 'https://github.com/BerkleyTechnologyServices/restdocs-spec'
      weight: 4
    - name: PhantomJS Maven Plugin
      url: '/phantomjs-maven-plugin'
      weight: 5
    - name: Resume
      url: 'https://www.linkedin.com/in/kylelieber'
      weight: 3
    - name: Development
      url: /categories/development
      weight: 2
    - name: Blog
      url: /
      weight: 1
params:
  author: Kyle Lieber
  bitbucket: 'https://bitbucket.org/klieber/'
  disqusShortname: kylelieber
  github: 'https://github.com/klieber/'
  github_repo_count: 5
  github_show_profile_link: true
  github_skip_forks: false
  github_user: klieber
  googleAnalytics: UA-52118741-1
  hljsStyle: solarized-dark
  linkedin: 'https://www.linkedin.com/in/kylelieber'
  rss: true
  searchEngineURL: 'https://www.google.com/search'
  stackoverflow: 'https://stackoverflow.com/users/1190144/kyle'
  subtitle: some things I felt like writing about...
  twitter: 'https://twitter.com/kylelieber/'
permalinks:
  post: '/:year/:month/:slug'
