baseurl = "http://kylelieber.com"
canonifyurls = true
languageCode = "en-us"
theme = "hugo-octopress"
title = "Kyle Lieber"
[[menu.main]]
name = "PhantomJS Maven Plugin"
url = "http://kylelieber.com/phantomjs-maven-plugin"
weight = 4
[[menu.main]]
name = "Resume"
url = "https://www.linkedin.com/in/kylelieber"
weight = 3
[[menu.main]]
name = "Development"
url = "/categories/development"
weight = 2
[[menu.main]]
name = "Blog"
url = "/"
weight = 1
[params]
author = "Kyle Lieber"
bitbucket = "https://bitbucket.org/klieber/"
disqusShortname = "kylelieber"
github = "https://github.com/klieber/"
github_repo_count = 5
github_show_profile_link = true
github_skip_forks = false
github_user = "klieber"
googleAnalytics = "UA-52118741-1"
hljsStyle = "solarized-dark"
linkedin = "https://www.linkedin.com/in/kylelieber"
rss = true
search_engine_url = "https://www.google.com/search"
stackoverflow = "http://stackoverflow.com/users/1190144/kyle"
subtitle = "some things I felt like writing about..."
twitter = "https://twitter.com/kylelieber/"
[permalinks]
post = "/:year/:month/:slug"
